FROM node:20

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN apt-get update && apt-get install -y python3 python3-pip

RUN pip3 install google-genai pillow

EXPOSE 8001

CMD ["node", "workers/scan.worker.js"]