FROM node:20

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Install Python
RUN apt-get update && apt-get install -y python3 python3-pip python3-venv

# Create virtual environment
RUN python3 -m venv /opt/venv

# Activate venv
ENV PATH="/opt/venv/bin:$PATH"

# Install Python packages inside venv
RUN pip install --upgrade pip

RUN pip install google-genai pillow

CMD ["node", "workers/scan.worker.js"]